image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init
    #init: |
      # optional: use a custom MySQL config.
      #sudo cp .gp/conf/mysql/my.cnf /etc/mysql/my.cnf
    command: |
      until nc -z 127.0.0.1 3306; do echo "waiting for mysql ..."; sleep 1; done
      cat $GITPOD_REPO_ROOT/data/mysql/*.sql | mysql -u root
  - init: |
      cd server
      chmod a+x mvnw
      ./mvnw clean install -U -DskipTests
    command: |
      cd server 
      ./mvnw spring-boot:run
    name: Start Backend
  - init: |
      cd client
      npx -p @angular/cli analytics off
      npm install
    command: |
      cd client
      npx -p @angular/cli serve
    name: Start Frontend
  - name: MySQL 
    command: |
      until nc -z 127.0.0.1 3306; do echo "waiting for mysql ..."; sleep 1; done
      multitail /var/log/mysql/error.log -I /var/log/mysql/mysql.log
  - name: Bash


ports:
  # Spring
  - port: 8080
    name: Backend
    onOpen: ignore
  # Angular
  - port: 4200
    name: Frontend
    onOpen: open-preview
    visibility: public
  # MySQL
  - port: 3306
    onOpen: ignore
    name: Database
    visibility: public

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - eamodio.gitlens
    - Angular.ng-template

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

gitConfig:
  alias.st: status
  alias.pr: pull --rebase

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
      - AngularJS
      - com.intellij.spring
      - com.intellij.spring.mvc
      - com.intellij.spring.data
      - com.intellij.spring.integration
      - Lombook Plugin
    prebuilds:
      version: both
